### ISSUE TITLE
The example of database

### ISSUE THREAD

**Issue by ghost** [VladKha/MovieNet#1]
Hi Vlad,

Thank you for the project. I am learning django and your project is very useful. Could you please provide the example of database?

**Comment by VladKha** [comment]
Hi, @ReichKV 

Glad that the project came in handy for you
Sure, there are backups for Country, Genre, Person and Movie tables (load them in this order)
[Data_sample.zip](https://github.com/VladKha/MovieNet/files/1492308/Data_sample.zip)

Regards

**Comment by VladKha** [comment]
@ReichKV Can I mark this issue as resolved?

**Comment by ghost** [comment]
Thank you. The issue is closed.
